#ifndef GAME_UI_GAME_CVARS_HPP
#define GAME_UI_GAME_CVARS_HPP

#include "console/CVar.hpp"

extern CVar* g_minimapPortalMaxCVar;
extern CVar* g_showToastBroadcastCVar;
extern CVar* g_showToastConversationCVar;
extern CVar* g_ShowClassColorInNameplateCVar;
extern CVar* g_assistAttackCVar;
extern CVar* g_autoClearAFKCVar;
extern CVar* g_autoDismountCVar;
extern CVar* g_autoDismountFlyingCVar;
extern CVar* g_autoLootDefaultCVar;
extern CVar* g_autoSelfCastCVar;
extern CVar* g_autoStandCVar;
extern CVar* g_autoUnshiftCVar;
extern CVar* g_autojoinBGVoiceCVar;
extern CVar* g_autojoinPartyVoiceCVar;
extern CVar* g_blockTradesCVar;
extern CVar* g_buffDurationsCVar;
extern CVar* g_chatBubblesCVar;
extern CVar* g_chatBubblesPartyCVar;
extern CVar* g_combatDamageCVar;
extern CVar* g_combatHealingCVar;
extern CVar* g_combatLogRetentionTimeCVar;
extern CVar* g_currencyTokensBackpack1CVar;
extern CVar* g_currencyTokensBackpack2CVar;
extern CVar* g_currencyTokensUnused1CVar;
extern CVar* g_currencyTokensUnused2CVar;
extern CVar* g_cvAutoInteract;
extern CVar* g_deselectOnClickCVar;
extern CVar* g_displayFreeBagSlotsCVar;
extern CVar* g_displayWorldPVPObjectivesCVar;
extern CVar* g_enablePVPNotifyAFKCVar;
extern CVar* g_guildMemberNotifyCVar;
extern CVar* g_guildRecruitmentChannelCVar;
extern CVar* g_guildShowOfflineCVar;
extern CVar* g_lootUnderMouseCVar;
extern CVar* g_minimapInsideZoomCVar;
extern CVar* g_minimapZoomCVar;
extern CVar* g_nameplateShowEnemiesCVar;
extern CVar* g_nameplateShowEnemyGuardiansCVar;
extern CVar* g_nameplateShowEnemyPetsCVar;
extern CVar* g_nameplateShowEnemyTotemsCVar;
extern CVar* g_nameplateShowFriendlyGuardiansCVar;
extern CVar* g_nameplateShowFriendlyPetsCVar;
extern CVar* g_nameplateShowFriendlyTotemsCVar;
extern CVar* g_nameplateShowFriendsCVar;
extern CVar* g_petMeleeDamageCVar;
extern CVar* g_petSpellDamageCVar;
extern CVar* g_predictedHealthCVar;
extern CVar* g_predictedPowerCVar;
extern CVar* g_previewTalentsCVar;
extern CVar* g_profanityFilterCVar;
extern CVar* g_questPOICVar;
extern CVar* g_removeChatDelayCVar;
extern CVar* g_rotateMinimapCVar;
extern CVar* g_screenEdgeFlashCVar;
extern CVar* g_scriptErrorsCVar;
extern CVar* g_secureAbilityToggleCVar;
extern CVar* g_serviceTypeFilterCVar;
extern CVar* g_showLootSpamCVar;
extern CVar* g_showTargetCastbarCVar;
extern CVar* g_showTargetOfTargetCVar;
extern CVar* g_showVKeyCastbarCVar;
extern CVar* g_spamFilterCvar;
extern CVar* g_stopAutoAttackOnTargetChangeCVar;
extern CVar* g_targetOfTargetModeCVar;
extern CVar* g_threatWarningCVar;
extern CVar* g_threatWorldTextCVar;
extern CVar* g_trackerSortingCVar;
extern CVar* g_unitHighlightsCVar;
extern CVar* s_cvAutoFilledMultiCastSlots;
extern CVar* s_cvAutoRangedCombat;
extern CVar* s_cvCalendarShowBattlegrounds;
extern CVar* s_cvCalendarShowDarkmoon;
extern CVar* s_cvCalendarShowLockouts;
extern CVar* s_cvCalendarShowResets;
extern CVar* s_cvCalendarShowWeeklyHolidays;
extern CVar* s_cvCombatLogPeriodicSpells;
extern CVar* s_cvLfdCollapsedHeaders;
extern CVar* s_cvLfdSelectedDungeons;
extern CVar* s_cvLfgSelectedRoles;
extern CVar* s_cvNameplateAllowOverlap;
extern CVar* s_cvQuestLogCollapseFilter;
extern CVar* s_cvShowAllSpellRanks;
extern CVar* s_cvShowToastFriendRequest;
extern CVar* s_cvShowToastOffline;
extern CVar* s_cvShowToastOnline;
extern CVar* s_cvThreatPlaySounds;
extern CVar* s_cvThreatShowNumeric;

bool AutoInteractStateChangedCallback(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool CVarHandler_autoCompleteResortNamesOnRecency(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool CVarHandler_autoCompleteUseContext(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool CVarHandler_autoCompleteWhenEditingFromCenter(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool CVarHandler_GuildRecruitmentMode(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool CVarHandler_ThreatWarning(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool GuildShowOfflineCallback(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool SetCalendarFilterCVarCallback(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool ShowClassColorInNameplateCallback(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool SignalPreviewTalentPointsChanged(CVar* cvar, const char* oldValue, const char* newValue, void* arg);
bool UnitHighlightsCVarCallback(CVar* cvar, const char* oldValue, const char* newValue, void* arg);

#endif // GAME_UI_GAME_CVARS_HPP
