#ifndef CLIENTOBJECT_PLAYER_C_HPP
#define CLIENTOBJECT_PLAYER_C_HPP

#include <cstdint>
#include "clientobject/CGObject_C.hpp"
#include "clientobject/Unit_C.hpp"
#include "clientobject/WGUID.hpp"

class CreatureModelDataRec;


const CreatureModelDataRec* Player_C_GetModelName(uint32_t race, uint32_t sex);
uint32_t Player_C_GetDisplayId(uint32_t race, uint32_t sex);

struct CGLocalPlayerData {
    WGUID PLAYER_FIELD_INV_SLOT_HEAD[23];
    WGUID PLAYER_FIELD_PACK_SLOT_1[16];
    WGUID PLAYER_FIELD_BANK_SLOT_1[28];
    WGUID PLAYER_FIELD_BANKBAG_SLOT_1[7];
    WGUID PLAYER_FIELD_VENDORBUYBACK_SLOT_1[12];
    WGUID PLAYER_FIELD_KEYRING_SLOT_1[32];
    WGUID PLAYER_FIELD_CURRENCYTOKEN_SLOT_1[32];
    WGUID PLAYER_FARSIGHT;
    WGUID PLAYER__FIELD_KNOWN_TITLES;
    WGUID PLAYER__FIELD_KNOWN_TITLES1;
    WGUID PLAYER__FIELD_KNOWN_TITLES2;
    WGUID PLAYER_FIELD_KNOWN_CURRENCIES;
    uint32_t PLAYER_XP;
    uint32_t PLAYER_NEXT_LEVEL_XP;
    uint32_t PLAYER_SKILL_INFO_1_1[384];
    uint32_t PLAYER_CHARACTER_POINTS1;
    uint32_t PLAYER_CHARACTER_POINTS2;
    uint32_t PLAYER_TRACK_CREATURES;
    uint32_t PLAYER_TRACK_RESOURCES;
    float PLAYER_BLOCK_PERCENTAGE;
    float PLAYER_DODGE_PERCENTAGE;
    float PLAYER_PARRY_PERCENTAGE;
    uint32_t PLAYER_EXPERTISE;
    uint32_t PLAYER_OFFHAND_EXPERTISE;
    float PLAYER_CRIT_PERCENTAGE;
    float PLAYER_RANGED_CRIT_PERCENTAGE;
    float PLAYER_OFFHAND_CRIT_PERCENTAGE;
    float PLAYER_SPELL_CRIT_PERCENTAGE1[7];
    uint32_t PLAYER_SHIELD_BLOCK;
    float PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE;
    uint32_t PLAYER_EXPLORED_ZONES_1[128];
    uint32_t PLAYER_REST_STATE_EXPERIENCE;
    uint32_t PLAYER_FIELD_COINAGE;
    uint32_t PLAYER_FIELD_MOD_DAMAGE_DONE_POS[7];
    uint32_t PLAYER_FIELD_MOD_DAMAGE_DONE_NEG[7];
    uint32_t PLAYER_FIELD_MOD_DAMAGE_DONE_PCT[7];
    uint32_t PLAYER_FIELD_MOD_HEALING_DONE_POS;
    float PLAYER_FIELD_MOD_HEALING_PCT;
    float PLAYER_FIELD_MOD_HEALING_DONE_PCT;
    uint32_t PLAYER_FIELD_MOD_TARGET_RESISTANCE;
    uint32_t PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE;
    uint32_t PLAYER_FIELD_BYTES;
    uint32_t PLAYER_AMMO_ID;
    uint32_t PLAYER_SELF_RES_SPELL;
    uint32_t PLAYER_FIELD_PVP_MEDALS;
    uint32_t PLAYER_FIELD_BUYBACK_PRICE_1[12];
    uint32_t PLAYER_FIELD_BUYBACK_TIMESTAMP_1[12];
    uint32_t PLAYER_FIELD_KILLS;
    uint32_t PLAYER_FIELD_TODAY_CONTRIBUTION;
    uint32_t PLAYER_FIELD_YESTERDAY_CONTRIBUTION;
    uint32_t PLAYER_FIELD_LIFETIME_HONORBALE_KILLS;
    uint32_t PLAYER_FIELD_BYTES2;
    uint32_t PLAYER_FIELD_WATCHED_FACTION_INDEX;
    uint32_t PLAYER_FIELD_COMBAT_RATING_1[25];
    uint32_t PLAYER_FIELD_ARENA_TEAM_INFO_1_1[21];
    uint32_t PLAYER_FIELD_HONOR_CURRENCY;
    uint32_t PLAYER_FIELD_ARENA_CURRENCY;
    uint32_t PLAYER_FIELD_MAX_LEVEL;
    uint32_t PLAYER_FIELD_DAILY_QUESTS_1[25];
    float PLAYER_RUNE_REGEN_1[4];
    uint32_t PLAYER_NO_REAGENT_COST_1[3];
    uint32_t PLAYER_FIELD_GLYPH_SLOTS_1[6];
    uint32_t PLAYER_FIELD_GLYPHS_1[6];
    uint32_t PLAYER_GLYPHS_ENABLED;
    uint32_t PLAYER_PET_SPELL_POWER;
};

struct CGPlayerData : CGLocalPlayerData {
    WGUID PLAYER_DUEL_ARBITER;
    uint32_t PLAYER_FLAGS;
    uint32_t PLAYER_GUILDID;
    uint32_t PLAYER_GUILDRANK;
    uint32_t PLAYER_BYTES;
    uint32_t PLAYER_BYTES_2;
    uint32_t PLAYER_BYTES_3;
    uint32_t PLAYER_DUEL_TEAM;
    uint32_t PLAYER_GUILD_TIMESTAMP;
    uint32_t PLAYER_QUEST_LOG_1_1;
    uint32_t PLAYER_QUEST_LOG_1_2;
    uint32_t PLAYER_QUEST_LOG_1_3[2];
    uint32_t PLAYER_QUEST_LOG_1_4;
    uint32_t PLAYER_QUEST_LOG_2_1;
    uint32_t PLAYER_QUEST_LOG_2_2;
    uint32_t PLAYER_QUEST_LOG_2_3[2];
    uint32_t PLAYER_QUEST_LOG_2_5;
    uint32_t PLAYER_QUEST_LOG_3_1;
    uint32_t PLAYER_QUEST_LOG_3_2;
    uint32_t PLAYER_QUEST_LOG_3_3[2];
    uint32_t PLAYER_QUEST_LOG_3_5;
    uint32_t PLAYER_QUEST_LOG_4_1;
    uint32_t PLAYER_QUEST_LOG_4_2;
    uint32_t PLAYER_QUEST_LOG_4_3[2];
    uint32_t PLAYER_QUEST_LOG_4_5;
    uint32_t PLAYER_QUEST_LOG_5_1;
    uint32_t PLAYER_QUEST_LOG_5_2;
    uint32_t PLAYER_QUEST_LOG_5_3[2];
    uint32_t PLAYER_QUEST_LOG_5_5;
    uint32_t PLAYER_QUEST_LOG_6_1;
    uint32_t PLAYER_QUEST_LOG_6_2;
    uint32_t PLAYER_QUEST_LOG_6_3[2];
    uint32_t PLAYER_QUEST_LOG_6_5;
    uint32_t PLAYER_QUEST_LOG_7_1;
    uint32_t PLAYER_QUEST_LOG_7_2;
    uint32_t PLAYER_QUEST_LOG_7_3[2];
    uint32_t PLAYER_QUEST_LOG_7_5;
    uint32_t PLAYER_QUEST_LOG_8_1;
    uint32_t PLAYER_QUEST_LOG_8_2;
    uint32_t PLAYER_QUEST_LOG_8_3[2];
    uint32_t PLAYER_QUEST_LOG_8_5;
    uint32_t PLAYER_QUEST_LOG_9_1;
    uint32_t PLAYER_QUEST_LOG_9_2;
    uint32_t PLAYER_QUEST_LOG_9_3[2];
    uint32_t PLAYER_QUEST_LOG_9_5;
    uint32_t PLAYER_QUEST_LOG_10_1;
    uint32_t PLAYER_QUEST_LOG_10_2;
    uint32_t PLAYER_QUEST_LOG_10_3[2];
    uint32_t PLAYER_QUEST_LOG_10_5;
    uint32_t PLAYER_QUEST_LOG_11_1;
    uint32_t PLAYER_QUEST_LOG_11_2;
    uint32_t PLAYER_QUEST_LOG_11_3[2];
    uint32_t PLAYER_QUEST_LOG_11_5;
    uint32_t PLAYER_QUEST_LOG_12_1;
    uint32_t PLAYER_QUEST_LOG_12_2;
    uint32_t PLAYER_QUEST_LOG_12_3[2];
    uint32_t PLAYER_QUEST_LOG_12_5;
    uint32_t PLAYER_QUEST_LOG_13_1;
    uint32_t PLAYER_QUEST_LOG_13_2;
    uint32_t PLAYER_QUEST_LOG_13_3[2];
    uint32_t PLAYER_QUEST_LOG_13_5;
    uint32_t PLAYER_QUEST_LOG_14_1;
    uint32_t PLAYER_QUEST_LOG_14_2;
    uint32_t PLAYER_QUEST_LOG_14_3[2];
    uint32_t PLAYER_QUEST_LOG_14_5;
    uint32_t PLAYER_QUEST_LOG_15_1;
    uint32_t PLAYER_QUEST_LOG_15_2;
    uint32_t PLAYER_QUEST_LOG_15_3[2];
    uint32_t PLAYER_QUEST_LOG_15_5;
    uint32_t PLAYER_QUEST_LOG_16_1;
    uint32_t PLAYER_QUEST_LOG_16_2;
    uint32_t PLAYER_QUEST_LOG_16_3[2];
    uint32_t PLAYER_QUEST_LOG_16_5;
    uint32_t PLAYER_QUEST_LOG_17_1;
    uint32_t PLAYER_QUEST_LOG_17_2;
    uint32_t PLAYER_QUEST_LOG_17_3[2];
    uint32_t PLAYER_QUEST_LOG_17_5;
    uint32_t PLAYER_QUEST_LOG_18_1;
    uint32_t PLAYER_QUEST_LOG_18_2;
    uint32_t PLAYER_QUEST_LOG_18_3[2];
    uint32_t PLAYER_QUEST_LOG_18_5;
    uint32_t PLAYER_QUEST_LOG_19_1;
    uint32_t PLAYER_QUEST_LOG_19_2;
    uint32_t PLAYER_QUEST_LOG_19_3[2];
    uint32_t PLAYER_QUEST_LOG_19_5;
    uint32_t PLAYER_QUEST_LOG_20_1;
    uint32_t PLAYER_QUEST_LOG_20_2;
    uint32_t PLAYER_QUEST_LOG_20_3[2];
    uint32_t PLAYER_QUEST_LOG_20_5;
    uint32_t PLAYER_QUEST_LOG_21_1;
    uint32_t PLAYER_QUEST_LOG_21_2;
    uint32_t PLAYER_QUEST_LOG_21_3[2];
    uint32_t PLAYER_QUEST_LOG_21_5;
    uint32_t PLAYER_QUEST_LOG_22_1;
    uint32_t PLAYER_QUEST_LOG_22_2;
    uint32_t PLAYER_QUEST_LOG_22_3[2];
    uint32_t PLAYER_QUEST_LOG_22_5;
    uint32_t PLAYER_QUEST_LOG_23_1;
    uint32_t PLAYER_QUEST_LOG_23_2;
    uint32_t PLAYER_QUEST_LOG_23_3[2];
    uint32_t PLAYER_QUEST_LOG_23_5;
    uint32_t PLAYER_QUEST_LOG_24_1;
    uint32_t PLAYER_QUEST_LOG_24_2;
    uint32_t PLAYER_QUEST_LOG_24_3[2];
    uint32_t PLAYER_QUEST_LOG_24_5;
    uint32_t PLAYER_QUEST_LOG_25_1;
    uint32_t PLAYER_QUEST_LOG_25_2;
    uint32_t PLAYER_QUEST_LOG_25_3[2];
    uint32_t PLAYER_QUEST_LOG_25_5;
    uint32_t PLAYER_VISIBLE_ITEM_1_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_1_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_2_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_2_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_3_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_3_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_4_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_4_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_5_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_5_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_6_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_6_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_7_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_7_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_8_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_8_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_9_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_9_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_10_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_10_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_11_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_11_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_12_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_12_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_13_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_13_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_14_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_14_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_15_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_15_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_16_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_16_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_17_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_17_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_18_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_18_ENCHANTMENT;
    uint32_t PLAYER_VISIBLE_ITEM_19_ENTRYID;
    uint32_t PLAYER_VISIBLE_ITEM_19_ENCHANTMENT;
    uint32_t PLAYER_CHOSEN_TITLE;
    uint32_t PLAYER_FAKE_INEBRIATION;
    uint32_t PLAYER_FIELD_PAD_0;
};

class CGPlayer {
    public:
    CGPlayerData* m_player;
    void* m_playerMirror;

    // OFFSET: 0x4F5530
    static uint32_t TotalFields() {
        return CGUnit::TotalFields() + 1043;
    }

    // OFFSET: 0x4F5540
    static uint32_t TotalRemoteFields() {
        return CGUnit::TotalFields() + 173;
    }

    static uint32_t GetDataSize() {
        return CGUnit::GetDataSize() + sizeof(CGPlayerData);
    }

    static uint32_t GetRemoteDataSize() {
        return CGUnit::GetDataSize() + sizeof(CGPlayerData) - sizeof(CGLocalPlayerData);
    }
};

class CGPlayer_C : public CGUnit_C, public CGPlayer {
    public:
    CGPlayer_C();
    CGPlayer_C(CClientObjCreate& objCreate, uint32_t time);
    void PostInit(uint32_t time, CClientObjCreate* objCreate, bool isUpdate3);

    static void SetStorage(CGPlayer_C* obj, uintptr_t descriptorPtr, uintptr_t mirrorPtr);
};


#endif // CLIENTOBJECT_PLAYER_C_HPP
