#ifndef CLIENTOBJECT_TYPES_HPP
#define CLIENTOBJECT_TYPES_HPP


enum UNIT_SEX {
    UNITSEX_MALE = 0x0,
    UNITSEX_FEMALE = 0x1,
    UNITSEX_NONE = 0x2,
    UNITSEX_LAST = 0x3,
    UNITSEX_BOTH = 0x3,
};

enum TypeMask : uint32_t {
    TYPEMASK_OBJECT = 0x1,
    TYPEMASK_ITEM = 0x2,
    TYPEMASK_CONTAINER = 0x4,
    TYPEMASK_UNIT = 0x8,
    TYPEMASK_PLAYER = 0x10,
    TYPEMASK_GAMEOBJECT = 0x20,
    TYPEMASK_DYNAMICOBJECT = 0x40,
    TYPEMASK_CORPSE = 0x80,
};

enum OBJECT_TYPE {
    TYPE_OBJECT = 0x1,
    TYPE_ITEM = 0x2,
    TYPE_CONTAINER = 0x4,
    TYPE_UNIT = 0x8,
    TYPE_PLAYER = 0x10,
    TYPE_GAMEOBJECT = 0x20,
    TYPE_DYNAMICOBJECT = 0x40,
    TYPE_CORPSE = 0x80,
    // TODO
    HIER_TYPE_OBJECT = TYPE_OBJECT,
    HIER_TYPE_ITEM = TYPE_OBJECT | TYPE_ITEM,
    HIER_TYPE_CONTAINER = TYPE_OBJECT | TYPE_ITEM | TYPE_CONTAINER,
    HIER_TYPE_UNIT = TYPE_OBJECT | TYPE_UNIT,
    HIER_TYPE_PLAYER = TYPE_OBJECT | TYPE_UNIT | TYPE_PLAYER,
    HIER_TYPE_GAMEOBJECT = TYPE_OBJECT | TYPE_GAMEOBJECT,
    HIER_TYPE_DYNAMICOBJECT = TYPE_OBJECT | TYPE_DYNAMICOBJECT,
    HIER_TYPE_CORPSE = TYPE_OBJECT | TYPE_CORPSE,
    // TODO
};

enum OBJECT_TYPE_ID {
    ID_OBJECT = 0,
    ID_ITEM = 1,
    ID_CONTAINER = 2,
    ID_UNIT = 3,
    ID_PLAYER = 4,
    ID_GAMEOBJECT = 5,
    ID_DYNAMICOBJECT = 6,
    ID_CORPSE = 7,
    NUM_CLIENT_OBJECT_TYPES,
    // TODO
};

enum UpdateType : uint8_t {
    UPDATE_PARTIAL = 0,
    UPDATE_MOVEMENT = 1,
    UPDATE_FULL = 2,
    UPDATE_3 = 3,
    UPDATE_OUT_OF_RANGE = 4,
    UPDATE_IN_RANGE = 5,
};


#endif
